apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-cfg
data:
  jupyterhub_config.py: "print('The configMap has been overrided')"
  jupyterhub_admins: ""
  gpu_mode: ""
  singleuser_pvc_size: 10Gi
